 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           2          40  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           2          41  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           2          42  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           2          42  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           3          40  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           3          41  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           3          42  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           3          42  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           4          41  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)         239          41  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)         239          41  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)         239          42  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)         240          40  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)         240          40  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)         240          41  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)         240          41  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)         240          42  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)         240          42  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)         240          43  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)         240          43  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           1          40  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           1          40  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           1          42  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           1          42  Might need more frequent remeshing?                                                                                                                            
 Loops:       78000 Time[Ma]:   6.2358665631535581E-002
  Found at (i,j)           1          42  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           5          49  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           5          50  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           5          50  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           5          51  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           6          52  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           6          53  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           6          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)         239          50  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           7          51  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           7          51  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)         240          51  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           1          53  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           1          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           1          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           1          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           1          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           1          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           1          49  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           1          50  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           1          51  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           1          52  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           1          53  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          53  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          50  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          51  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          51  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          51  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          52  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          52  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           3          52  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           2          53  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           3          53  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           3          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           3          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           3          49  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           3          50  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           3          50  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           3          51  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           3          51  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          51  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          52  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          52  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          53  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          53  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          53  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          50  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          50  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          50  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           4          51  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           5          53  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           5          53  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           5          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           5          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      282800 Time[Ma]:  0.22609223556625893     
  Found at (i,j)           5          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)         240          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)         239          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)         239          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)         239          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)         239          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           1          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           2          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           2          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)         238          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           1          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           2          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           2          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           2          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           2          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           2          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           3          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           3          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           3          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           3          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           3          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           3          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           3          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           4          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           4          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      417800 Time[Ma]:  0.33402207902908931     
  Found at (i,j)           5          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)         239          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)         239          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)         240          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)           1          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      485600 Time[Ma]:  0.38822684485708853     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         237          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         237          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         237          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         237          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           4          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         238          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         238          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         238          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         238          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           2          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           5          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         239          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         239          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         239          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         239          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         239          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         239          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           4          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           2          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           2          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           2          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           2          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           2          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           3          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           4          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           4          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           4          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           4          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           4          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           4          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           5          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)           5          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         240          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         240          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      557600 Time[Ma]:  0.44578942803726473     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           6          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         235          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         235          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           4          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         236          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         236          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         236          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         236          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         236          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         236          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         236          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         236          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         237          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         237          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         237          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         237          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         237          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           3          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           4          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          54  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           5          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         238          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           2          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           3          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           3          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           4          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         235          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         239          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           2          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           2          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           3          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           2          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           3          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           2          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           2          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           2          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           2          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           3          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           3          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           4          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           4          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           4          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           3          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      630600 Time[Ma]:  0.50415149153938776     
  Found at (i,j)           5          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           2          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           2          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         234          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         235          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           3          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           4          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         235          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           3          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           3          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         235          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           4          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         235          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           3          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           4          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           4          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         239          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           4          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         236          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         234          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         236          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         236          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         236          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         237          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         236          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         239          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         237          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         236          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         237          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         237          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         237          55  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         237          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         236          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         237          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           3          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           2          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           4          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           5          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           2          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         236          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           4          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         239          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           2          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         234          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         237          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         237          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         238          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         239          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         239          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         239          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          56  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      705000 Time[Ma]:  0.56363282749223653     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      794800 Time[Ma]:  0.63542616040306732     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      794800 Time[Ma]:  0.63542616040306732     
  Found at (i,j)         239          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      794800 Time[Ma]:  0.63542616040306732     
  Found at (i,j)         239          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      794800 Time[Ma]:  0.63542616040306732     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      794800 Time[Ma]:  0.63542616040306732     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      794800 Time[Ma]:  0.63542616040306732     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      794800 Time[Ma]:  0.63542616040306732     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           2          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           1          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           2          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           4          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           4          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           2          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           2          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           2          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           2          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           3          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      887800 Time[Ma]:  0.70977783034412822     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         238          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         239          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         238          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           2          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         238          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         239          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         239          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           1          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           1          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         238          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         239          60  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           1          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         239          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         239          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         239          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         237          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          57  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         240          59  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)           2          58  Might need more frequent remeshing?                                                                                                                            
 Loops:      983200 Time[Ma]:  0.78604825305786163     
  Found at (i,j)         238          59  Might need more frequent remeshing?                                                                                                                            
